server:
  port: 6000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/productdb?createDatabaseIfNotExist=true
    username: devuser
    password: password
  application:
    name: product-service
  config:
    import: optional:configserver:http://localhost:8888
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        ddl-auto: update
    show-sql: true
